language: r
cache: packages
warnings_are_errors: false

r_packages:
  - ape
  - covr
  - data.table
  - ggplot2
  - knitr
  - phytools
  - reshape2
  - rmarkdown
  - XML

r_github_packages:
  - jimhester/lintr
  - jimhester/covr
  - MangoTheCat/goodpractice

before_install:
  - tlmgr install index

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'library(goodpractice); gp()'
